name = "fortuno-mpi"
version = "0.1.0"
license = "BSD-2-Clause-Patent"
author = "Fortuno authors"
maintainer = "aradi@uni-bremen.de"
copyright = "Copyright 2024, Fortuno authors"

[fortran]
# Enabling the implicit options seems to be necessary for using fpm with meta-dependency mpi.
# Do not worry, the project does not make use of them. ;-)
implicit-typing = true
implicit-external = true
source-form = "free"

[dependencies]
mpi = "*"
